"use client";
import { useState } from "react";
import { WidgetGrid } from "@/components/widget-grid";
import { WidgetGridFreeform } from "@/components/widget-grid-freeform";
import { WidgetEditorToolbar } from "@/components/widget-editor-toolbar";
import type { LayoutConfig } from "@/lib/dashboard-layout";
import { freeformToV1, v1ToFreeform, type FreeformLayoutConfig } from "@/lib/freeform-layout";
import { saveDashboardLayoutAction, resetDashboardLayoutAction } from "../dashboard-layout-actions";
import type { Role } from "@/types/role";
export const DEFAULT_LOCATIONS_LAYOUT: LayoutConfig = { version:1, widgets:[{id:"geo-cities",type:"geo-kpi-cities",size:"md"},{id:"geo-top",type:"geo-kpi-top-city",size:"md"},{id:"geo-avg",type:"geo-kpi-avg-per-city",size:"md"},{id:"geo-map",type:"geo-map",size:"lg"},{id:"geo-ranked",type:"geo-ranked-cities",size:"md"}] };
export function LocationsGrid({projectId,locationData,totalVisits,visitsWithCity,layout,role}:{projectId:string;locationData:Array<{city:string;count:number}>;totalVisits:number;visitsWithCity:number;layout?:LayoutConfig|FreeformLayoutConfig|null;role?:Role}) {
 const initial=layout??DEFAULT_LOCATIONS_LAYOUT; const [rendered,setRendered]=useState<LayoutConfig|FreeformLayoutConfig>(initial); const [draft,setDraft]=useState<LayoutConfig|FreeformLayoutConfig>(initial); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const admin=role==="PLATFORM_ADMIN"||role==="CLIENT_ADMIN"; const data={summary:{totalVisits,uniqueStores:locationData.length,minDate:null,maxDate:null},installSlots:[],metrics:[],visitRows:[],dailyVisits:[],photoByKind:{},locations:locationData}; const grid=(value:LayoutConfig|FreeformLayoutConfig, edit=false)=>value.version===2?<WidgetGridFreeform layout={value} projectId={projectId} data={data} editable={edit} onChangeLayout={edit?setDraft:undefined}/>:<WidgetGrid layout={value} projectId={projectId} data={data} editable={edit} onChangeLayout={edit?setDraft:undefined} gridTemplateRows="92px minmax(0,1fr)"/>;
 if(!admin)return grid(rendered); return <div className="flex h-full min-h-0 flex-col"><WidgetEditorToolbar editing={editing} saving={saving} error={error} onStartEdit={()=>{setDraft(rendered);setEditing(true)}} onAddWidget={()=>{}} onReset={async()=>{setSaving(true);try{await resetDashboardLayoutAction(projectId,"locations");setRendered(DEFAULT_LOCATIONS_LAYOUT);setDraft(DEFAULT_LOCATIONS_LAYOUT);setEditing(false)}catch(e){setError(e instanceof Error?e.message:"Reset failed")}finally{setSaving(false)}}} onSave={async()=>{setSaving(true);try{const result=await saveDashboardLayoutAction(projectId,draft,"manual","locations");setRendered(result.layout);setEditing(false)}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}} onCancel={()=>{setDraft(rendered);setEditing(false)}} advanced={draft.version===2} onToggleAdvanced={()=>setDraft(d=>d.version===1?v1ToFreeform(d):window.confirm("Switching back to standard layout mode will re-arrange widgets to the nearest standard size — this can't be perfectly undone. Continue?")?freeformToV1(d):d)}/><div className="min-h-0 flex-1">{grid(editing?draft:rendered,editing)}</div></div>;
}
