"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";
import { MapPin, BarChart3, TrendingUp } from "lucide-react";
import type { WidgetProps } from "@/lib/widget-registry";
const GeoHeatMap = dynamic(() => import("@/components/charts/geo-heat-map").then((m) => m.GeoHeatMap), { ssr: false });
function values(data: WidgetProps["data"]) { const rows = data.locations ?? []; const total = rows.reduce((n, row) => n + row.count, 0); return { rows, total, cities: rows.length, top: rows[0], avg: rows.length ? Math.round(total / rows.length) : 0 }; }
export function GeoKpiCities(p: WidgetProps) { const v=values(p.data); return <Kpi icon={<MapPin className="h-4 w-4"/>} label="Cities" value={String(v.cities)} sub="with visits" className={p.className}/>; }
export function GeoKpiTopCity(p: WidgetProps) { const v=values(p.data); return <Kpi icon={<TrendingUp className="h-4 w-4"/>} label="Top City" value={v.top?.city ?? "—"} sub={v.top && v.total ? `${Math.round(v.top.count/v.total*100)}% of visits` : ""} className={p.className}/>; }
export function GeoKpiAverage(p: WidgetProps) { const v=values(p.data); return <Kpi icon={<BarChart3 className="h-4 w-4"/>} label="Avg / City" value={String(v.avg)} sub="visits per city" className={p.className}/>; }
export function GeoMap(p: WidgetProps) { const [hovered,setHovered]=useState<string|null>(null); const rows=useMemo(()=>p.data.locations?.slice(0,30)??[],[p.data.locations]); return <div className={`${p.className??""} card-ventriloc flex flex-col p-3 min-h-0`}><span className="text-sm font-medium text-foreground">Geographic Distribution</span><div className="flex-1 min-h-0 mt-1"><GeoHeatMap data={rows} hoveredCity={hovered} onCityHover={setHovered}/></div></div>; }
export function GeoRankedCities(p: WidgetProps) { const router=useRouter(); const rows=p.data.locations?.slice(0,12)??[]; const max=Math.max(1,...rows.map(r=>r.count)); return <div className={`${p.className??""} card-ventriloc flex flex-col p-3 min-h-0`}><span className="text-sm font-medium text-foreground mb-2">Ranked Cities</span><div className="flex-1 min-h-0 overflow-y-auto space-y-1.5">{rows.map((r,i)=><button key={r.city} onClick={()=>router.push(`/dashboard/projects/${p.projectId}/visits?city=${encodeURIComponent(r.city)}`)} className="w-full flex items-center gap-2 rounded-md px-2 py-1.5 text-left hover:bg-muted/50"><span className="text-[10px] w-4">{i+1}</span><span className="text-[11px] flex-1 truncate">{r.city}</span><div className="w-16 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-[#ff682c]" style={{width:`${r.count/max*100}%`}}/></div><span className="text-[10px] w-6 text-right">{r.count}</span></button>)}</div></div>; }
function Kpi({icon,label,value,sub,className}:{icon:React.ReactNode;label:string;value:string;sub:string;className?:string}) { return <div className={`${className??""} card-ventriloc p-2 flex flex-col justify-between gap-0.5`}><div className="flex justify-between text-[9px] uppercase text-muted-foreground"><span>{label}</span><span className="text-signal-orange">{icon}</span></div><div className="font-space-grotesk text-xl truncate">{value}</div><div className="text-[9px] text-muted-foreground truncate">{sub}</div></div>; }
